//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchebnaya_pr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deals
    {
        public int Id { get; set; }
        public int Demand_Id { get; set; }
        public int Supply_Id { get; set; }
    
        public virtual demands demands { get; set; }
        public virtual supplies supplies { get; set; }
    }
}
